# Generated by Django 3.2.25 on 2025-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
