# Generated by Django 3.2.25 on 2025-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTime', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('add', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
