# Generated by Django 3.2.25 on 2025-07-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTime', '0005_auto_20250708_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='registers',
            name='password',
        ),
    ]
